printWidth: 100
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
requirePragma: false
insertPragma: false
proseWrap: preserve
